name: Letcode WDIO Regression

on:
  # schedule:
  #   - cron:  '0 23 * * *' #7AM PHT
  #   - cron:  '0 08 * * *' #4PM PHT
  workflow_dispatch:

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    
    env:
      HEADLESS: ${{ secrets.HEADLESS }}
      BASE_URL: ${{ secrets.BASE_URL }}
      ELM_TIMEOUT: ${{ secrets.BASE_URL }}
      DEBUG: ${{ secrets.DEBUG }}
      RANDOM_USER_API_URL: ${{ secrets.RANDOM_USER_API_URL }}
      RANDOM_USER_API_ENDPOINT: ${{ secrets.RANDOM_USER_API_ENDPOINT }}
      #GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Update Chromedriver
      if: always()
      run: npm uninstall chromedriver && npm install chromedriver@latest
        
    - name: Run WDIO Test
      if: always()
      run: npm run ciregression
    
